version: "3.8"
services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: truckgps
      POSTGRES_PASSWORD: truckgps
      POSTGRES_DB: truckgps
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://truckgps:truckgps@db:5432/truckgps
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/app

  frontend:
    build: ./frontend
    ports:
      - "4173:4173"
    volumes:
      - ./frontend:/app

volumes:
  - db_data:
